services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: invoice_tracker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Mukul@2401
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 5

  redis:
    image: redis:7

  web:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000

  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redis
      - db
    env_file:
      - .env
    volumes:
      - .:/app
    command: celery -A celery_worker worker --loglevel=info

volumes:
  postgres_data:
